name: "Migration from travis"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - compiler: gcc-4.8
            os: ubuntu-latest
            use_conan: yes
          - compiler: clang
            os: macos-latest
        
    runs-on: ${{ matrix.os }}
    container: ubuntu:16.04

    steps:
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        #add-apt-repository ppa:ubuntu-toolchain-r/test
        apt-get update
        apt-get install -y linux-libc-dev texlive texinfo valgrind gcc-4.8-multilib g++-4.8 \
          wget make libssl-dev libcurl4-openssl-dev expat-devel
        wget https://github.com/git/git/archive/v2.18.2.zip -O git.zip
        unzip git.zip
        rm git.zip
        cd git-*
        make prefix=/usr/local all
        sudo make prefix=/usr/local install
        cd ..
        
    - uses: actions/checkout@v3
      with:
        fetch-depth: 5
        submodules: true
        
    - run: |
        if [ "${{matrix.os}}" = "ubuntu-latest" ]; then
          os="linux"
        elif [ "${{matrix.os}}" = "osx" ]; then
          os="linux"
        fi     
        echo "TRAVIS_OS_NAME=$os" >> $GITHUB_ENV
        echo "USE_CONAN=${{matrix.use_conan}}" >> $GITHUB_ENV

    - run: |
        ./.ci/travis_before_install.sh
        ./.ci/travis_install.sh
        ./.ci/travis_before_script.sh
        ./.ci/travis_script.sh
        ./.ci/travis_after_success.sh
