name: "Migration from travis"

on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  job1:

    strategy:
      fail-fast: true
      matrix:
        compiler: [ 'gcc-4.8', 'clang' ]
        os: [ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 5
        submodules: true

    - run: |
        pip install --upgrade pip
        pip install --user urllib3==1.26.16 cpp-coveralls
