name: "Migration from travis"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include: 
          - compiler: gcc-4.8
            os: ubuntu-latest
            use_conan: yes
          - compiler: clang
            os: macos-latest
        
    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ matrix.os == "ubuntu-latest" }}
      run: |
        sudo apt-get update
        sudo apt-get install gcc-4.8-multilib linux-libc-dev g++-4.8 texlive texinfo valgrind
        
    - uses: actions/checkout@v3
      with:
        fetch-depth: 5
        submodules: true
        
    - run: |
        if [ "${{matrix.os}}" = "ubuntu-latest" ]; then
          os="linux"
        elif [ "${{matrix.os}}" = "osx" ]; then
          os="linux"
        fi     
        echo "TRAVIS_OS_NAME=$os" >> $GITHUB_ENV
        echo "USE_CONAN=${{matrix.use_conan}}" >> $GITHUB_ENV

    - run: |
        ./.ci/travis_before_install.sh
        ./.ci/travis_install.sh
        ./.ci/travis_before_script.sh
        ./.ci/travis_script.sh
        ./.ci/travis_after_success.sh
